version: "3.9"
services:
  bot:
    build:
      context: ./bot
      dockerfile: .docker/Dockerfile    
    container_name: bot 
    environment:
      - DB_URI=mongodb://db:27017/rezultati?retryWrites=false
      - DB_NAME=rezultati
      - DISCORD_TOKEN=$DISCORD_TOKEN
      - LOG_CHANNEL_ID=$LOG_CHANNEL_ID
      - SECRET_SERVER=$SECRET_SERVER
      - SLEEP_DURATION_MIN=5
      - PRUNE_PERIOD_MIN=10
      - MAX_PAGE_SIZE=1000000
    restart: unless-stopped
  mongo:
    image: mongo
    container_name: db 
    volumes:
      - mongodata:/data/db
      - mongoconfig:/data/configdb
    ports:
      - 27017:27017
    restart: unless-stopped

volumes:
  mongodata:
  mongoconfig:
